### ISSUE TITLE
Allow to use --no-interaction option

### ISSUE THREAD

**Issue by mpodorov** [lcatlett/blt-drush-alias#1]
Please allow to use --no-interaction option (instead of the -y option which was removed from BLT) by adding the second parameter TRUE to confirm() method.
Please create a release. :)

**Comment by lcatlett** [comment]
This is resolved with https://github.com/lcatlett/blt-drush-alias/commit/cabf7c559b34d0a8089d09550cdba6371ae6deeb

**Comment by lcatlett** [comment]
@mpodorov - see https://github.com/lcatlett/blt-drush-alias/releases/tag/1.0.0 for the stable release including this fix :)

**Comment by mpodorov** [comment]
Thanks a lot for the plugin!
