### ISSUE TITLE
Incompatible with typhonius/acquia-php-sdk-v2:2.*

### ISSUE THREAD

**Issue by josephdpurcell** [lcatlett/blt-drush-alias#4]
The typhonius/acquia-php-sdk-v2 library is pinned to version 1 in this repo. Version 1 of the sdk has this issue: https://github.com/typhonius/acquia-php-sdk-v2/issues/71.

So, to resolve the issue either:
a) this library needs to allow tag 2.* of the sdk where the issue is fixed
b) the typhonius/acquia-php-sdk-v2 library needs a hotfix of the 1.* release

I've submitted a patch for (b) here: https://github.com/typhonius/acquia-php-sdk-v2/pull/72.

I don't know if (a) is feasible as there may be incompatibilities with the 2.* release of the sdk.

**Comment by typhonius** [comment]
I've updated and will tag `1.1.2` to unblock in the near term, although if we can bump the library to the v2 branch then that starts to unlock a lot of other functionality too. I'll take a look and see if I can create a PR against this repo with that branch.

**Comment by typhonius** [comment]
https://github.com/lcatlett/blt-drush-alias/pull/5

**Comment by lcatlett** [comment]
Closed with #5 and new release cut with v2 support: https://github.com/lcatlett/blt-drush-alias/releases/tag/2.0.0
